# Generated by Django 4.2.1 on 2023-06-12 13:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0008_importproduct_created_at_importproduct_is_confirmed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.shopprodcut'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
