# Generated by Django 4.2.1 on 2023-06-14 14:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0010_remove_product_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopprodcut',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shop_product', to='shop.product'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trade_product', to='shop.shopprodcut'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shop_trade', to=settings.AUTH_USER_MODEL),
        ),
    ]
